#pragma config(Sensor, S1,     se,             sensorEV3_Color)
#pragma config(Sensor, S2,     sm,             sensorEV3_Color)
#pragma config(Sensor, S3,     sd,             sensorEV3_Color)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorB,          me,            tmotorEV3_Large, openLoop, driveLeft, encoder)
#pragma config(Motor,  motorC,          md,            tmotorEV3_Large, openLoop, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void cruzamento()
{
	if(SensorValue[se] >= 20 && SensorValue[sm] >= 20 && SensorValue[sd] >= 20)
	{
		motor[me]=100;
		motor[md]=100;
	}
}

void curvaesquerda()
{
	if(SensorValue[se] >= 20 && SensorValue[sd] < 20)
	{
		motor[me]=40;
		motor[md]=90;
	}
}
void curvadireita()
{
	if(SensorValue[se] < 20 && SensorValue[sd] >= 20)
	{
		motor[me]=90;
		motor[md]=40;
	}
}
void linha()
{
	if(SensorValue[se] < 20 && SensorValue[sm] >= 20 && SensorValue[sd] < 20)
	{
		motor[me]=100;
		motor[md]=100;
	}
}

task main()
{
	delay(3000);
	motor[me]=100;
	motor[md]=100;
	clearTimer(T1);

	while(time1[T1] < 60000)
		{
			linha();
			cruzamento();
			curvaesquerda();
			curvadireita();
		}
}
